### ISSUE TITLE
Up to date LibRaw and rawspeed

### ISSUE THREAD

**Issue by moowgle** [FMeinicke/QtRaw#1]
Thank you for this wonderful fork, it's right that what I need (getting QtRaw under Windows to work is a pain).

Is there any possible way of keeping LibRaw and rawspeed up-to-date? I'm not really a pro in git patches and what I've encountered with were various problems when I try to pull in current master branches of both repositories. Although it would be nice to have up-to-date libraw so I can opt in changes to use together with Canon's new CR3 format.

Many thanks.
Jan

**Comment by FMeinicke** [comment]
Hi. Glad that I could help with this fork!

I'll have to admit that I didn't use QtRaw for quite a while now, which is why LibRaw and rawspeed are out of date. I'll see what I can do to update the libraries to their most recent stable versions.

**Comment by moowgle** [comment]
@FMeinicke This would be very nice! What I currently try is also to get a 64-bit version working of it. A little bit complex because iconv, zlib and libxml2 binaries are also 32-bit. 

I currently work on a bigger type of closed software and I really would like to integrate it. Thank you for looking into it!

**Comment by FMeinicke** [comment]
Ok, so I just pushed a new branch called [update-64bit](https://github.com/FMeinicke/QtRaw/tree/update-64bit). It uses the latest stable releases of LibRaw (v0.19.5) and rawspeed (v3.3).  
Since rawspeed was easier to build with 64-bit MinGW and you wanted a 64-bit version anyway, I figured I save myself some hassle and make it work for 64-bit right away. I updated the instruction for installation of rawspeeds dependencies in the README since those have to be 64-bit as well.

Also, because LibRaw had some breaking changes in the repository you might need to do a clean clone of QtRaw. I don't know how these changes are going to be integrated when you simply check out the new branch and pull from it.

Let me know if this solves the issue for you!

**Comment by moowgle** [comment]
~~As I can see from the GitLab repo QtRaw did not have some major changes since your fork so I just try with the branch...~~ give me a minute.

I did not look close enough. I try to opt in newest qtraw.

**Comment by moowgle** [comment]
First issue I encountered was:

```
../../rawspeed/src/librawspeed/decompressors/JpegDecompressor.cpp:35:10: fatal error: jpeglib.h: No such file or directory
 #include <jpeglib.h>                      // for jpeg
          ^~~~~~~~~~~
compilation terminated.
```

What I've seen inside patch ``rawspeed.pro``  was the switch to:
```
win32: {
    INCLUDEPATH *= $$PWD/../third-party/zlib-64/include \
        $$PWD/../third-party/libjpeg-turbo-64/include
    LIBS+=-L$$PWD/../third-party/zlib-64/lib/ -lz \
          -L$$PWD/../third-party/libjpeg-turbo-64/lib -ljpeg
    LIBS+=-lws2_32 -fopenmp
}
```

but the folders in third party do not have the ``64`` extra. Edited them manually now its working perfectly fine. Will try out with CR3 file now (I think I'll need to edit some source of QtRaw)...

**Comment by moowgle** [comment]
So I built with newest QtRaw and everything worked fine except I get a black output anytime I try open up an image:

```
TIFFReadDirectory: Warning, Photometric tag is missing, assuming data is YCbCr.
TIFFReadDirectory: Warning, SamplesPerPixel tag is missing, applying correct SamplesPerPixel value of 3.
foo: Old-style JPEG compression support is not configured.
TIFFReadDirectory: Warning, Photometric tag is missing, assuming data is YCbCr.
TIFFReadDirectory: Warning, SamplesPerPixel tag is missing, applying correct SamplesPerPixel value of 3.
foo: Old-style JPEG compression support is not configured.
foo: Sorry, requested compression method is not configured.
```

Everything is right now on the same base as my macOS version was. Except I did not use rawspeed.

And this is just with CR2 files...

**Comment by moowgle** [comment]
Hey @FMeinicke,

I looked a little bit deeper into the problem and what I think is that probably libjpeg-turbo is not linked against libraw. When I look into the [patch file of the master branch](https://github.com/FMeinicke/QtRaw/blob/26c80c81630f6bb5b89a2414d005f0a62021554c/patches/LibRaw.patch#L31) I can clearly see the point where libjpeg-turbo is linked to it. When I look into the [patch file of the update-64bit branch](https://github.com/FMeinicke/QtRaw/blob/update-64bit/patches/LibRaw.patch) I cannot find a similar section. 

Could you help me out here? We're close to our goal!

**Comment by FMeinicke** [comment]
OK, I'll look into all of that tomorrow. I'm afraid I won't have time today.

**Comment by FMeinicke** [comment]
So, first of, thanks for your effort and patience. I'll go through your posts in chronological order:
1. The issue with the *-64* suffix was my bad. I needed a way to distinguish the 64-bit libs from the already present 32-bit ones. I took this suffix out now.
2. I did as you suggested and added libjpeg to the link libraries of libraw. However, there might be another problem that could cause the black output you see. Did you get the black output on a Windows or macOS machine? It wasn't quite clear to read from [this](https://github.com/FMeinicke/QtRaw/issues/1#issuecomment-583854409) post. The issue I found while trying it on my Windows machine was that the dependencies of `qtraw.dll` (i.e. `libraw.dll`, `rawspeed.dll`, `libjpeg-62.dll` and `libz.dll`) weren't installed to the correct directory for the application to find all of these libs. Therefore the QtRaw plugin could not be loaded properly. You can check if QtRaw was loaded successfully by setting the `QT_DEBUG_PLUGINS` environment variable to `1` before running the application.  
And another thing: Did you try to open the image with the example application that comes with this repository or did you use a custom application that you wrote yourself? If it's the latter then please try with the provided example application to rule out any that there is anything wrong with your application.

**Comment by moowgle** [comment]
Hello. Thanks for investigating!

I see the black output on my Windows machine. I thought I am on the same installation base (qtraw in imageformats dir etc.) as on my Mac we're everything works fine.

I also built my own little application where I was testing, because in the example I did not even get the option to select raw files in file browser.

How do I set ``QT_DEBUG_PLUGINS`` to get output?

**Comment by moowgle** [comment]
Thats what I get from QT_DEBUG_PLUGINS

```
Got keys from plugin meta data ("tiff", "tif")
QFactoryLoader::QFactoryLoader() looking at "E:/Qt/5/12LTS/5.12.7/mingw73_64/plugins/imageformats/qtraw.dll"
Found metadata in lib E:/Qt/5/12LTS/5.12.7/mingw73_64/plugins/imageformats/qtraw.dll, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "crw",
            "cr2",
            "arw",
            "nef",
            "raf",
            "dng",
            "rw2"
        ]
    },
    "archreq": 0,
    "className": "RawPlugin",
    "debug": false,
    "version": 330752
}


"The plugin 'E:/Qt/5/12LTS/5.12.7/mingw73_64/plugins/imageformats/qtraw.dll' uses incompatible Qt library. (Cannot mix debug and release libraries.)" 
         not a plugin
```

**Comment by moowgle** [comment]
UPDATE! So I got it working when I switch my application to RELEASE mode and adding the libs output folder to Systems PATH. Any thoughts how I also can build it for debug mode and without adding it to path? I build and run QtRaw from command line.

**Comment by FMeinicke** [comment]
> I also built my own little application where I was testing, because in the example I did not even get the option to select raw files in file browser.

Right, that's what I thought. This is clearly an indicator that the QtRaw plugin wasn't loaded properly. Because if it was the example application would allow you to select the different raw formats.

Ok, so it seems to be exactly the issue I mentioned:
> The issue I found while trying it on my Windows machine was that the dependencies of `qtraw.dll` (i.e. `libraw.dll`, `rawspeed.dll`, `libjpeg-62.dll` and `libz.dll`) weren't installed to the correct directory for the application to find all of these libs. Therefore the QtRaw plugin could not be loaded properly. 

I'm currently still working on that. I'll let you know when I fixed that!

**Comment by FMeinicke** [comment]
I think I found a solution now. All DLLs should now be installed to the correct directories. I also added a `d` suffix for LibRaw and rawspeed if they are built in debug mode (i.e. they're now called `librawd.dll` and `librawspeedd.dll`). So you should now be able to simply build and install QtRaw once and then all of your applications should automatically find and use the QtRaw imageformats plugin.  
See and check if this works for you now in both debug and release mode, please.

**Comment by moowgle** [comment]
OMG! It works just fine! I needed to copy the ``qtrawd.dll`` manually to the imageformats folder anyway but it works just out of the box! Thank you very very much, you're definitely going to be named in the application 😃

**Comment by moowgle** [comment]
BOOM! CR3 JUST WORKS! 😄

**Comment by FMeinicke** [comment]
I'm really glad to hear that it works now! However, I would like to fix that problem with the location of `qtrawd.dll` as well. According to the `src.pro` file ([here](https://github.com/FMeinicke/QtRaw/blob/9fa38899e0218e2b9a4a3abe5e2e7aabce7b23ba/src/src.pro#L35)) it should be put into the imageformats folder automatically... Did you add the `make install` build step?

**Comment by moowgle** [comment]
I build from command line with ``mingw32-make -j8`` and ``mingw32-make install``. This builds automatically the release version. After that there is no ``qtrawd`` in build output. When I then build also using ``mingw32-make -j8 debug`` it gives me a ``qtrawd`` file in the output folder. Only problem here is if I then call ``mingw32-make install`` it just copies the ``qtraw`` file into the imageformats folder.

**Comment by FMeinicke** [comment]
Ah, ok. Well, I can definitely say it works using QtCreator if you add a build step as described in the README:
> Finally you are ready to build QtRaw. Open the qtraw.pro file with QtCreator. Go into the 'Projects' tab on the left and add a build step. Select 'Make' and give it `install` as 'Make arguments'. Then just hit 'Build' and that's it.

If you don't like t use QtCreator you could try to run `qmake "CONFIG+=debug" <path/to/qtraw.pro>`. I haven't tested if this does what you want but this is the command QtCreator calls when building the debug version. So I suppose this could also work on the command line.

If this does not work you can try to manually install the debug version of the QtRaw DLL by executing  `mingw32-make debug-install` while inside the `build/src` directory.

Since this isn't an issue that directly regards QtRaw but rather qmake/mingw32-make I'm going to close this issue.  
Again, I'm very happy to help if you have any further questions or suggestions. :D

**Comment by moowgle** [comment]
Again, many thanks! I hope deployment goes easy as well. I probably need to include the LibRaw and rawspeed dll files when I ship it... no second testing machine currently around here... but when I come back home I will try out. I'll give you an update when I finished the application and as said you're going to be mentioned :smile:

**Comment by FMeinicke** [comment]
Yes, you will need to deploy `libraw.dll`, `rawspeed.dll`, `libjpeg-62.dll` and `libz.dll` into the same directory where you deploy your application so that it can find the libraries and load the QtRaw plugin.

Feel free to ask if you come across any further issues or problems.

**Comment by FMeinicke** [comment]
Oh, and since everything's working fine now I'm going to merge everything into the master branch. Just so you know.
